### ISSUE TITLE
Test video

### ISSUE THREAD

**Issue by Zippen-Huang** [ROBOTIS-JAPAN-GIT/turtlebot3_slam_3d#3]
can you list the test video on youtube, I want to watch the effect of your algorithm

**Comment by Affonso-Gui** [comment]
Added a gif to the readme file.

You can also see the original (better quality) .mp4 video by clicking on the gif.

**Comment by Zippen-Huang** [comment]
It is wonderful, 3Q！

**Comment by Affonso-Gui** [comment]
Thanks!
