### ISSUE TITLE
 Transform error: Failed to lookup transformation from map to zed_left_camera_frame

### ISSUE THREAD

**Issue by neoneo1716** [ROBOTIS-JAPAN-GIT/turtlebot3_slam_3d#5]
i have a tx2 and zed camera and has been set up the environment ,but when i run the launch file turtlebot3_zed_bringup.launch  or turtlebot3_slam_3d.launch ,my ros can't receive the /map ,i look up the rostopic ,i find there are the camera topic and map topic ,but the rviz can't display the mapdate and pointcould, what should i do? 
[ERROR] [1547872278.454724]: Error opening serial: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'

**Comment by Affonso-Gui** [comment]
Usually `/dev/ttyACM0` is the port assigned to the OpenCR (the board connecting the motors to the single board computer), so I am guessing the program is failing around [here](https://github.com/ROBOTIS-JAPAN-GIT/turtlebot3_slam_3d/blob/master/launch/turtlebot3_zed_bringup.launch#L4), before it can actually start the camera or the mapping itself.

Are you using a real Turtlebot3 or just trying out the package connecting the camera directly to the PC?

If it is the first case, make sure that the [setup](http://emanual.robotis.com/docs/en/platform/turtlebot3/setup/#setup) is alright and make sure to launch the bringup node `turtlebot3_zed_bringup.launch` directly from the single board computer.

By the way did the demo bag files work out?

Also, it would be helpful to have a look at the `frames.pdf` generated by `rosrun tf view_frames` as well.

**Comment by neoneo1716** [comment]
ok ,thank you for you reply.in my case ,i just connecting the camera to the pc.but i dont' know why can't do that? i just want to test the camera how to build map




------------------ 原始邮件 ------------------
发件人: "Affonso, Guilherme"<notifications@github.com>;
发送时间: 2019年1月21日(星期一) 晚上7:11
收件人: "ROBOTIS-JAPAN-GIT/turtlebot3_slam_3d"<turtlebot3_slam_3d@noreply.github.com>;
抄送: "魂々殇"<597478922@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ROBOTIS-JAPAN-GIT/turtlebot3_slam_3d]  Transform error: Failedto lookup transformation from map to zed_left_camera_frame (#5)




Usually /dev/ttyACM0 is the port assigned to the OpenCR (the board connecting the motors to the single board computer), so I am guessing the program is failing around here, before it can actually start the camera or the mapping itself.
 
Are you using a real Turtlebot3 or just trying out the package connecting the camera directly to the PC?
 
If it is the first case, make sure that the setup is alright and make sure to launch the bringup node turtlebot3_zed_bringup.launch directly from the single board computer.
 
By the way did the demo bag files work out?
 
Also, it would be helpful to have a look at the frames.pdf generated by rosrun tf view_frames as well.

**Comment by Affonso-Gui** [comment]
You can also run the mapping/detection with only the camera, but some modifications to the launch files would be needed, such as:

- Commenting out the Turtlebot3 launch:
https://github.com/ROBOTIS-JAPAN-GIT/turtlebot3_slam_3d/blob/master/launch/turtlebot3_zed_bringup.launch#L4

- Changing some of the RTABMAP parameters, such as the bellow
https://github.com/ROBOTIS-JAPAN-GIT/turtlebot3_slam_3d/blob/master/launch/rtabmap.launch#L13-L14

Would probably be a better idea to try to start with the examples of the RTABMAP (mapping) and YOLO (detection) separately, and then try out this package to combine them.

That is:
- https://github.com/stereolabs/zed-ros-wrapper/tree/master/examples/zed_rtabmap_example
- https://pjreddie.com/darknet/yolo/

**Comment by t-kitajima** [comment]
As there have been no updates, I am closing this issue.

**Comment by kdr193** [comment]
I know this is late, but just try this:
sudo chown $USER /dev/ttyACM0
