### ISSUE TITLE
detection_publisher drops all the time when the localisation flag is on

### ISSUE THREAD

**Issue by mhhabdelwahab** [ROBOTIS-JAPAN-GIT/turtlebot3_slam_3d#6]
Hi,
detection_publisher drops all the time when the localisation flag is on. This is the error I got.

[detection_collector-13] process has died [pid 24949, exit code 1, cmd /home/sscrovers/catkin_ws/src/slam_3d/scripts/detection_publisher.py __name:=detection_collector __log:=/home/sscrovers/.ros/log/903a794a-968b-11e9-9dec-7c5cf8826c11/detection_collector-13.log].
log file: /home/sscrovers/.ros/log/903a794a-968b-11e9-9dec-7c5cf8826c11/detection_collector-13*.log

Thanks,

**Comment by Affonso-Gui** [comment]
Hello, 

Does that log file have any relevant information? Does the file `~/.ros/detections_dbscan.db` exists? (it should be auto-generated if everything goes well) If it does, can you run the `detection_publisher.py` from command line?

This also might be some version issue. Are you using python3?

If I'm not mistaken that was only a visualization script for getting the names on rviz, if you are in a hurry you should be able to just comment that out and run the code normally while we are debugging on this thread.

Best regards

**Comment by mhhabdelwahab** [comment]
Hi Affonso,
Thanks for your reply.
I found there was an error in the package name when I ran the detection_publisher.py separately.
Thanks a lot.
Kind regards,
Mohamed
