### ISSUE TITLE
Can turtlebot3 be replaced by turtlebot2？

### ISSUE THREAD

**Issue by willzoe** [ROBOTIS-JAPAN-GIT/turtlebot3_slam_3d#8]
I have a turtlebot2.
Can I just use zed as a 3D sensor without using an RGBD camera or lidar?

**Comment by t-kitajima** [comment]
@willzoe 

As your question is related to turtlebot2 & zed rather than TB3, Would you ask the question at the link below?
[https://answers.ros.org/questions]()

Regards,
